### ISSUE TITLE
Accelerated scrolling in Safari bug

### ISSUE THREAD

**Issue by icidasset** [Morhaus/react-list-view#5]
When scrolling in Safari (OS X El Capitan), the accelerated scrolling halts when the new items are added (ie. on render). I tried to find a solution, but couldn't find anything. Any ideas?

I made two small videos to show the problem:

Your demo/example: https://www.dropbox.com/s/np8qkcw8p61161d/react-list-view-1.mov?dl=0
My application: https://www.dropbox.com/s/gfrbnybjg1syq1c/react-list-view-2.mov?dl=0

Thanks! (also for this wonderful library)

**Comment by alexkirsz** [comment]
Strange, I can't reproduce this issue on Safari 9.0.1.

Might be related to the "fix" for #2. Try overriding the `position` css property of your elements to `absolute` instead of `fixed`.

```
renderItem={(x, y, style) => <div style={{ ...style, position: 'absolute' }}>Item #{x}</div>}
```

**Comment by icidasset** [comment]
Thanks for the quick reply!
I tried to change the position property, but no luck.
After a lot of trial and error, I found something that "works".
If you add `pointer-events: none` to `.ReactListView-container`, the issue is gone.
But then I can't use click events anymore :disappointed:
This is hella weird... especially because you can't reproduce this.

**Comment by alexkirsz** [comment]
Ahah! I noticed that disabling pointer events could improve scrolling performance a lot. You could try disabling pointer events only while scrolling.

**Comment by icidasset** [comment]
That sounds like a good idea!
As it seems to be a browser-specific bug, or whatever, I'm going to close this.
Thanks for the help!
