### ISSUE TITLE
Error in examples

### ISSUE THREAD

**Issue by phil-lauffenburger** [Morhaus/react-list-view#6]
I get the following errors running npm install and npm start:

ERROR in multi main
Module not found: Error: Cannot resolve module 'webpack-dev-server/client' in /Users/philiplauffenburger/Documents/Coding/react/listViewTut/react-list-view
 @ multi main
webpack: bundle is now VALID.

**Comment by alexkirsz** [comment]
Fixed in 39c7718f12d03ba22b018b8424802c168f0fff77
