### ISSUE TITLE
Horizontal list view doesn't scroll

### ISSUE THREAD

**Issue by aymericbouzy** [Morhaus/react-list-view#9]
This is my component : 

``` jsx
<ReactListView
  style={{flex: 1}}
  columnWidth={50}
  columnCount={30}
  renderItem={(x, y, style) => {
    return (
      <div style={{...style, height: "100%"}}>
        Hello
        <br />
        world!
      </div>
    )
  }}
  />
```

It doesn't scroll. If I add the `rowHeight` and `rowCount` props, it does, but I would like my columns to take the full height and not set them at a fixed height.

**Comment by alexkirsz** [comment]
Hey Aymeric,

I've defaulted the scroll container's height to 100%. That should fix your issue.

The fix is in 1.0.0.
